# Generated by Django 6.0.5 on 2026-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
