# Generated by Django 6.0.7 on 2026-08-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_remove_client_email_remove_client_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='vente.commande'),
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
        migrations.DeleteModel(
            name='ModePaiement',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
