# Generated by Django 6.0.7 on 2026-08-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0004_remove_paiement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
